# Generated by Django 5.1.3 on 2024-11-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hear_rate', models.IntegerField()),
                ('o2_sangre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_corporal', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tiempo_tomado', models.DateTimeField()),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteFamiliarUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIoTproject.familiar')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIoTproject.paciente')),
            ],
        ),
    ]
