# Generated by Django 5.1.3 on 2024-11-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIoTproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='contraseña',
            field=models.CharField(default='contra', max_length=128),
        ),
        migrations.AddField(
            model_name='familiar',
            name='usuario',
            field=models.CharField(default='user', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(default='firstname', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='apellido',
            field=models.CharField(default='firstname', max_length=100),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nombre',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
